"""Add cascade delete to summary

Revision ID: 387c38d7d8fe
Revises: b6d0fdceb8dc
Create Date: 2025-06-18 10:00:08.855164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387c38d7d8fe'
down_revision: Union[str, None] = 'b6d0fdceb8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('summaries_article_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_article_id_fkey'), 'summaries', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###
