"""init

Revision ID: b6d0fdceb8dc
Revises: 
Create Date: 2025-06-17 19:31:30.157648

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b6d0fdceb8dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['articles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.create_table('summaries',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('article_id', sa.Integer(), nullable=False),
                    sa.Column('summary', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('article_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summaries')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
